// Generated by gencpp from file ersow_comm/data_agent3.msg
// DO NOT EDIT!


#ifndef ERSOW_COMM_MESSAGE_DATA_AGENT3_H
#define ERSOW_COMM_MESSAGE_DATA_AGENT3_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ersow_comm
{
template <class ContainerAllocator>
struct data_agent3_
{
  typedef data_agent3_<ContainerAllocator> Type;

  data_agent3_()
    : agent3_value(0)
    , agent3_posx(0)
    , agent3_posy(0)
    , agent3_post(0)
    , agent3_ballx(0)
    , agent3_bally(0)
    , agent3_ball_detected(0)
    , agent3_pass(0)
    , agent3_condition(0)  {
    }
  data_agent3_(const ContainerAllocator& _alloc)
    : agent3_value(0)
    , agent3_posx(0)
    , agent3_posy(0)
    , agent3_post(0)
    , agent3_ballx(0)
    , agent3_bally(0)
    , agent3_ball_detected(0)
    , agent3_pass(0)
    , agent3_condition(0)  {
  (void)_alloc;
    }



   typedef int32_t _agent3_value_type;
  _agent3_value_type agent3_value;

   typedef uint16_t _agent3_posx_type;
  _agent3_posx_type agent3_posx;

   typedef uint16_t _agent3_posy_type;
  _agent3_posy_type agent3_posy;

   typedef uint16_t _agent3_post_type;
  _agent3_post_type agent3_post;

   typedef uint16_t _agent3_ballx_type;
  _agent3_ballx_type agent3_ballx;

   typedef uint16_t _agent3_bally_type;
  _agent3_bally_type agent3_bally;

   typedef uint16_t _agent3_ball_detected_type;
  _agent3_ball_detected_type agent3_ball_detected;

   typedef uint8_t _agent3_pass_type;
  _agent3_pass_type agent3_pass;

   typedef uint8_t _agent3_condition_type;
  _agent3_condition_type agent3_condition;





  typedef boost::shared_ptr< ::ersow_comm::data_agent3_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ersow_comm::data_agent3_<ContainerAllocator> const> ConstPtr;

}; // struct data_agent3_

typedef ::ersow_comm::data_agent3_<std::allocator<void> > data_agent3;

typedef boost::shared_ptr< ::ersow_comm::data_agent3 > data_agent3Ptr;
typedef boost::shared_ptr< ::ersow_comm::data_agent3 const> data_agent3ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ersow_comm::data_agent3_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ersow_comm::data_agent3_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ersow_comm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'ersow_comm': ['/home/khoirlnwar/COMM_workspace/src/ersow_comm/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ersow_comm::data_agent3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ersow_comm::data_agent3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ersow_comm::data_agent3_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ersow_comm::data_agent3_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ersow_comm::data_agent3_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ersow_comm::data_agent3_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ersow_comm::data_agent3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4236bf70894c8b40f3eee3b69d67749c";
  }

  static const char* value(const ::ersow_comm::data_agent3_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4236bf70894c8b40ULL;
  static const uint64_t static_value2 = 0xf3eee3b69d67749cULL;
};

template<class ContainerAllocator>
struct DataType< ::ersow_comm::data_agent3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ersow_comm/data_agent3";
  }

  static const char* value(const ::ersow_comm::data_agent3_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ersow_comm::data_agent3_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 agent3_value\n\
\n\
uint16 agent3_posx\n\
uint16 agent3_posy\n\
uint16 agent3_post\n\
\n\
uint16 agent3_ballx\n\
uint16 agent3_bally\n\
uint16 agent3_ball_detected\n\
\n\
uint8 agent3_pass\n\
uint8 agent3_condition\n\
";
  }

  static const char* value(const ::ersow_comm::data_agent3_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ersow_comm::data_agent3_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent3_value);
      stream.next(m.agent3_posx);
      stream.next(m.agent3_posy);
      stream.next(m.agent3_post);
      stream.next(m.agent3_ballx);
      stream.next(m.agent3_bally);
      stream.next(m.agent3_ball_detected);
      stream.next(m.agent3_pass);
      stream.next(m.agent3_condition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct data_agent3_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ersow_comm::data_agent3_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ersow_comm::data_agent3_<ContainerAllocator>& v)
  {
    s << indent << "agent3_value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.agent3_value);
    s << indent << "agent3_posx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_posx);
    s << indent << "agent3_posy: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_posy);
    s << indent << "agent3_post: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_post);
    s << indent << "agent3_ballx: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_ballx);
    s << indent << "agent3_bally: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_bally);
    s << indent << "agent3_ball_detected: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agent3_ball_detected);
    s << indent << "agent3_pass: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agent3_pass);
    s << indent << "agent3_condition: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.agent3_condition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ERSOW_COMM_MESSAGE_DATA_AGENT3_H
